# Generated by Django 4.1.3 on 2022-11-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter album name', max_length=200, verbose_name='Album title')),
                ('release_date', models.IntegerField(help_text='Enter album release year', verbose_name='Album release year')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_singer', models.CharField(help_text='Enter artist name', max_length=200, verbose_name='Artist name')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(help_text='Enter song title', max_length=200, verbose_name='Name of the song')),
                ('number', models.IntegerField(help_text='Enter the number of the song in the album', verbose_name='Album song number')),
                ('album', models.ManyToManyField(help_text='Choose an album name', to='catalog.album', verbose_name='Album title')),
                ('singer', models.ManyToManyField(help_text='Select artist name', to='catalog.singer', verbose_name='Artist name')),
            ],
        ),
    ]
