# Generated by Django 4.1.1 on 2023-01-08 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(help_text='Enter song title', max_length=200, verbose_name='Name of the song')),
                ('name_singer', models.CharField(help_text='Enter artist name', max_length=200, verbose_name='Artist name')),
                ('title', models.CharField(blank=True, help_text='Enter album name', max_length=200, null=True, verbose_name='Album title')),
                ('number', models.IntegerField(blank=True, help_text='Enter the number of the song in the album', null=True, verbose_name='Album song number')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_singer', models.CharField(help_text='Enter artist name', max_length=200, verbose_name='Artist name')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter album name', max_length=200, null=True, verbose_name='Album title')),
                ('name_singer', models.CharField(help_text='Enter artist name', max_length=200, verbose_name='Artist name')),
                ('release_date', models.IntegerField(blank=True, help_text='Enter album release year', null=True, verbose_name='Album release year')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
