# Generated by Django 4.1.3 on 2022-11-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите назание альбома', max_length=200, verbose_name='Название альбома')),
                ('release_date', models.IntegerField(help_text='Введите год выпуска альбома', verbose_name='Год выпуска альбома')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_singer', models.CharField(help_text='Введите имя исполнителя', max_length=200, verbose_name='Имя исполнителя')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(help_text='Введите название песни', max_length=200, verbose_name='Название песни')),
                ('number', models.IntegerField(help_text='Введите номер песни в альбоме', verbose_name='Номер песни в альбоме')),
                ('album', models.ManyToManyField(help_text='Выберите название альбома', to='catalog.album', verbose_name='Название альбома')),
                ('singer', models.ManyToManyField(help_text='Выберите имя исполнителя', to='catalog.singer', verbose_name='Имя исполнителя')),
            ],
        ),
    ]
